### PR TITLE
Fix tests, closes #16

### LINKED ISSUE #16: Ensure tests are not swallowing errors

### PR DESCRIPTION
**Pull request by reicruz**
@aeweidne 

Are we also moving towards using `portend` in our cognitive tests?

### CODE REVIEW

**Comment by aeweidne** [comment]
We probably should for good measure + consistency with documentation.  However, those tests are more stable than the regex tests because they emit directly and don't force into replies.

**Comment by reicruz** [comment]
I went ahead and updated the cognitive tests to use `portend` as well. I ran into issues when defining the promise **after** emitting the nlc event; `portend` was not picking up the first expected event. 

So per @nsand 's suggestion, I changed the tests to be more safe by declaring the promise before emitting and returning it after.

**Comment by nsand** [comment]
👍 looks awesome to me.

**Comment by reicruz** [comment]
Coverage went down 5%, investigating why before merge.

**Comment by reicruz** [comment]
Coverage up to 90%, this is ready to merge.

@aeweidne do you know why Coveralls comments changes unknown? I've seen it happen a couple of times on some PRs. It seems like it's not picking up the branch on Coveralls

**Comment by aeweidne** [comment]
I have also seen it and not sure what causes it... if you run locally and see the right coverage percent i wouldnt worry

**Comment by nsand** [comment]
@aeweidne Could the whole change to building only on master branch mess this up? The timing of these issues seem related.

**Comment by aeweidne** [comment]
When it builds for the PR shouldn't it be building the branch in question, though?

**Comment by reicruz** [comment]
Yea it should but if you check the branch list on Coveralls, it doesn't show up (no `issues/16`). Probably why it's **Unknown**.

screen shot 2016-09-08 at 2 52 15 pm

**Comment by aeweidne** [comment]
Interesting, I did notice that if you click on the build for this PR it says its building from `master`, not the head specified by this PR.

**Comment by aeweidne** [comment]
we could drop concurrent builds to 1 instead of whitelisting only the master branch

**Comment by aeweidne** [comment]
i'm hijacking this to experiment with npm connectivity

**Comment by aeweidne** [comment]
no idea why it's still unknown, we are generating coverage stats for issues/16 now, or should be

**Pull request merged**
